sudo: required
language: ruby
rvm: 2.3.3
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
services:
  - postgresql
install:
- rvm use 2.3.3 --install
before_script:
- RAILS_ENV=test bin/setup
script:
- RAILS_ENV=test bin/test
deploy:
  provider: deis
  controller: deis.prod.revelry.net
  app: lintron
  cli_version: v2.7.0
  username: travis-ci
  password:
    secure: "cROF7T9FqN2tFS0VUEznJZaqnioFD3EbsPng+Zz9KfX8+zsTMXhMSAnkC7eypFNfWp1P3xR/Udyvbb3qJSqB25dSh4zlwOsmTRdkePQYijD1Nn5vS18FBOw7hkZtP/G35ju2Ubj6bJ+cfAqpAlrmAeF5MtwhFyKodS9xBArG+ry1aj2Kqdnly+nLEh5G4hWzE7VKIGgZL2tcz9kwRrkcWLN68aE/QDo/bSrZRLaWE6gBRwZL/76XJBSHeSMk1B+LmNwbQ+ZmdxIs74rtN3OjuPihfjO98MchEtdwZg2cw/3lvxjf3IcGlgRqVMHauGiAZv4f2v+gGs789KytJ2iXWLc2OtjfLvoppTb90M87ffF+pHrKoscfxgFGAucXgaSBpONLxO6CzmVAO4eCCc5bJj6rM2krgV8ps++AslIZ2WFJZ/MwNwBVbLEBvZgyxpPUyI+F35TN96Rw6TcapfwJyfL2fgv19MALy2TYRDaCEF+iy44RNPa0tRd5fSAfe+R4ZkwYm3RL5Q5CDJ/6pqBxNicQAELF3G6wThVPYDHfm4eXbWaWX07gJeE0J0FA/SfMjAmsF+uSVbUPzVF/xRUY8DWzMvY80kmf1JuVPWhoXABtHWHUe7UMh1gSRRmlUKWjKTcN/J/dABYTvYpA627MmDuMmwpifxzBpwwLjUZA6aY="
  on:
    branch: master
after_deploy:
- ./deis run "rake db:migrate" -a lintron
