sudo: required
language: ruby
rvm: 2.3.3
addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
services:
  - postgresql
install:
- rvm use 2.3.3 --install
before_script:
- RAILS_ENV=test bin/setup
script:
- RAILS_ENV=test bin/test
deploy:
  provider: hephy
  controller: https://deis.prod.revelry.net
  app: lintron
  cli_version: v2.19.0
  username: travis-ci
  password:
    secure: "DxME/eoNn9BCSJog40W+mzGg97QPt55/tHeNpfP9Rp5aB3Opb0mN6ITsYW5WRGcyjW0bEZmI04+VlWrfVxx/sV56c3XfBc8FbkZgyt7dZhHv2emfsi2kOvblbeU9kEgZT35FaiJWxHu8SM9DgEafXyH8IxHV8JAk2tb95zxAfH2TETkMI4ssMXq6OQAio6x8pUhNjf+jTk5Hlk7K5hYR5FCqwd2PTKABBdDqefkp2AKx3P+Z4wSo4ogEwcsddHKMcgU6+8edounfDRUNW+7vco5LoTyHAeLzYwVm5MYc/5ByGDLKk3TqkDR3tP5SMrrTMwbNpEsnDiR0qpRQMc9whT/tPJ5sLfjDW6LW2EaXOm0XyLt35ZuaimoVO2zhMgObvungJjHGPg9dbi6s7rsI58MmJSH1cUdGe3s8Qo/QnfL4rl0mzmOuotygCGwVGAAnhPyxsQthBL4XusgR34AIspm9bmrdKRBgaRdJEyGs549jfDnAPq2N5Nj/+jIYkhOSSgGg/pBH1TUbQp1+A+0GChfrGaWVrex0TcL6nayKlFr1rRfn8hRMq7visvyceX1Q0+47TQXAD20FjNjRzacRzQlnmRjvcjBfKwhjA/HQx2O2wZIRIfeEv6u5A3oJpvJB4JRRWk10UbNsSeoQsaKqiEnvURXCRcSY8pLI0sWo3d0="
  on:
    branch: master
after_deploy:
- ./deis run "rake db:migrate" -a lintron
